package implslo

import (
	"context"

	"github.com/SigNoz/signoz/pkg/modules/dashboard"
	"github.com/SigNoz/signoz/pkg/types/dashboardtypes"
	"github.com/SigNoz/signoz/pkg/valuer"
)

func newID() string { return valuer.GenerateUUID().StringValue() }

// sloDashboardTitle is the stable title used to find and update the generated
// dashboard, so re-running generation never creates duplicates.
const sloDashboardTitle = "SLOs & Error Budgets [slo-generated]"

// generator creates and idempotently updates the SLO dashboard via the
// dashboard module.
type generator struct {
	dashboards dashboard.Module
}

func newGenerator(dashboards dashboard.Module) *generator {
	return &generator{dashboards: dashboards}
}

// Generate creates the SLO dashboard, or updates it in place if one with the
// stable title already exists. It is keyed by title so applying twice does not
// duplicate.
func (g *generator) Generate(ctx context.Context, orgID valuer.UUID, createdBy string, creator valuer.UUID) (*dashboardtypes.Dashboard, error) {
	data := buildSLODashboard()

	existing, err := g.dashboards.List(ctx, orgID)
	if err != nil {
		return nil, err
	}
	for _, d := range existing {
		if title, _ := d.Data["title"].(string); title == sloDashboardTitle {
			id, err := valuer.NewUUID(d.ID)
			if err != nil {
				return nil, err
			}
			return g.dashboards.Update(ctx, orgID, id, createdBy, dashboardtypes.UpdatableDashboard(data), 0)
		}
	}
	return g.dashboards.Create(ctx, orgID, createdBy, creator, dashboardtypes.SourceUser, dashboardtypes.PostableDashboard(data))
}

// buildSLODashboard assembles the dashboard data blob with one PromQL panel per
// slo.* metric.
func buildSLODashboard() dashboardtypes.StorableDashboardData {
	panels := []struct {
		title string
		query string
		unit  string
	}{
		{"SLO Compliance (SLI)", "slo_compliance", "percentunit"},
		{"Error Budget Remaining", "slo_error_budget_remaining", "percentunit"},
		{"Burn Rate", "slo_burn_rate", ""},
		{"Trust State (0 unhealthy, 1 healthy, 2 indeterminate)", "slo_state", ""},
	}

	widgets := make([]interface{}, 0, len(panels))
	layout := make([]interface{}, 0, len(panels))
	for i, p := range panels {
		id := newID()
		widgets = append(widgets, buildPromQLWidget(id, p.title, p.query, p.unit))
		layout = append(layout, map[string]interface{}{
			"i": id,
			"x": (i % 2) * 6,
			"y": (i / 2) * 6,
			"w": 6,
			"h": 6,
		})
	}

	return dashboardtypes.StorableDashboardData{
		"title":       sloDashboardTitle,
		"description": "Auto-generated by the SLO engine. SLI, error budget, burn rate, and trust state per SLO.",
		"tags":        []interface{}{"slo", "generated"},
		"version":     "v4",
		"variables":   map[string]interface{}{},
		"layout":      layout,
		"widgets":     widgets,
	}
}

// buildPromQLWidget builds a single time-series widget backed by a PromQL query.
func buildPromQLWidget(id, title, query, unit string) map[string]interface{} {
	return map[string]interface{}{
		"id":         id,
		"title":      title,
		"panelTypes": "graph",
		"yAxisUnit":  unit,
		"query": map[string]interface{}{
			"queryType": "promql",
			"promql": []interface{}{
				map[string]interface{}{
					"name":     "A",
					"query":    query,
					"legend":   "{{slo}}",
					"disabled": false,
				},
			},
			"builder": map[string]interface{}{
				"queryData":     []interface{}{},
				"queryFormulas": []interface{}{},
			},
			"clickhouse_sql": []interface{}{},
			"id":             newID(),
		},
	}
}
