package slo

import (
	"crypto/rand"
	"fmt"
)

// DashboardTitle is the stable title used to find and update the generated
// dashboard, so re-running generation never creates duplicates.
const DashboardTitle = "SLOs & Error Budgets [reliability-agent]"

// BuildDashboard assembles the SLO dashboard data blob (the classic
// /api/v1/dashboards widgets format) with one PromQL panel per slo_* metric.
func BuildDashboard() map[string]any {
	panels := []struct {
		title string
		query string
		unit  string
	}{
		{"SLO Compliance (SLI)", "slo_compliance", "percentunit"},
		{"Error Budget Remaining", "slo_error_budget_remaining", "percentunit"},
		{"Burn Rate", "slo_burn_rate", ""},
		{"Trust State (0 unhealthy, 1 healthy, 2 indeterminate)", "slo_state", ""},
	}

	widgets := make([]any, 0, len(panels))
	layout := make([]any, 0, len(panels))
	for i, p := range panels {
		id := newID()
		widgets = append(widgets, promQLWidget(id, p.title, p.query, p.unit))
		layout = append(layout, map[string]any{
			"i": id,
			"x": (i % 2) * 6,
			"y": (i / 2) * 6,
			"w": 6,
			"h": 6,
		})
	}

	return map[string]any{
		"title":       DashboardTitle,
		"description": "Auto-generated by the reliability agent. SLI, error budget, burn rate, and trust state per SLO.",
		"tags":        []any{"slo", "generated"},
		"version":     "v4",
		"variables":   map[string]any{},
		"layout":      layout,
		"widgets":     widgets,
	}
}

func promQLWidget(id, title, query, unit string) map[string]any {
	return map[string]any{
		"id":         id,
		"title":      title,
		"panelTypes": "graph",
		"yAxisUnit":  unit,
		"query": map[string]any{
			"queryType": "promql",
			"promql": []any{
				map[string]any{"name": "A", "query": query, "legend": "{{slo}}", "disabled": false},
			},
			"builder":        map[string]any{"queryData": []any{}, "queryFormulas": []any{}},
			"clickhouse_sql": []any{},
			"id":             newID(),
		},
	}
}

// newID returns a random RFC-4122 v4 UUID string.
func newID() string {
	var b [16]byte
	_, _ = rand.Read(b[:])
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}
